# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

jobs:
  # - job: CI
  #   steps:
  #     - script: "yarn"
  #       displayName: "install"

  #     - script: "yarn test:ci"
  #       displayName: "test ci frontend"

  #     - task: PublishTestResults@2
  #       inputs:
  #         testResultsFormat: "JUnit"
  #         testResultsFiles: "**/test-results/testResult.xml"

  #     - script: "yarn build"
  #       displayName: "build frontend"

  #     - publish: $(System.DefaultWorkingDirectory)/apps/client/dist
  #       artifact: WebApp
  - job: CD
    # dependsOn: CI

    steps:
      - script: "node --version"
        displayName: "node version"

      # - task: AzureCLI@2
      #   inputs:
      #     azureSubscription: ahk-service-connection
      #     scriptType: "bash"
      #     scriptLocation: "inlineScript"
      #     inlineScript: ls -R

      # - task: AzureCLI@2
      #   inputs:
      #     azureSubscription: ahk-service-connection
      #     scriptType: "bash"
      #     scriptLocation: "scriptPath"
      #     scriptPath: ./create-infra.sh

      # - task: AzureFileCopy@4
      #   inputs:
      #     SourcePath: # string. Required. Source.
      #     azureSubscription: ahk-service-connection
      #     Destination: "AzureBlob"
      #     storage: # string. Alias: StorageAccountRM. Required. RM Storage Account.
