# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CI
    steps:
      - script: "yarn"
        displayName: "install"

      - script: "yarn test:ci"
        displayName: "test ci frontend"

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: "**/test-results/testResult.xml"

      - script: "yarn build"
        displayName: "build frontend"

      - publish: $(System.DefaultWorkingDirectory)/apps/client/dist
        artifact: WebApp
